### ISSUE TITLE
Tests broke since 6b548f3e64b1944aa8af52c27d5b34feb0ada21c

### ISSUE THREAD

**Issue by QuLogic** [tdewolff/argp#2]
Tests passed on the previous commit, but are now panicing:
```
--- FAIL: TestArgpAdd (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55e4c7f24f26]

goroutine 85 [running]:
testing.tRunner.func1.2({0x55e4c7fdfe60, 0x55e4c80f7550})
	/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x55e4c7fdfe60?, 0x55e4c80f7550?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/tdewolff/argp.TestArgpAdd(0xc0001a4b60)
	/builddir/build/BUILD/golang-github-tdewolff-argp-0-build/argp-6b548f3e64b1944aa8af52c27d5b34feb0ada21c/_build/src/github.com/tdewolff/argp/argp_test.go:315 +0x1a6
testing.tRunner(0xc0001a4b60, 0x55e4c8007eb8)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/lib/golang/src/testing/testing.go:1742 +0x390
exit status 2
FAIL	github.com/tdewolff/argp	0.007s
```
Please consider adding CI.

**Comment by tdewolff** [comment]
Thanks, should be fixed now.
